do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'rol_usuario'
  ) then
    create type public.rol_usuario as enum ('superadmin', 'admin', 'operador');
  end if;
end
$$;

create table if not exists public.perfiles (
  id uuid primary key references auth.users (id) on delete cascade,
  correo text not null unique,
  nombre text,
  rol public.rol_usuario not null default 'operador',
  aprobado boolean not null default false,
  aprobado_en timestamptz,
  aprobado_por uuid references auth.users (id),
  creado_en timestamptz not null default timezone('utc', now())
);

create or replace function public.tocar_actualizado_en()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en := timezone('utc', now());
  return new;
end;
$$;

create or replace function public.usuario_actual_aprobado()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.perfiles
    where id = auth.uid()
      and aprobado = true
  );
$$;

create or replace function public.usuario_actual_es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.perfiles
    where id = auth.uid()
      and aprobado = true
      and rol in ('superadmin', 'admin')
  );
$$;

create or replace function public.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  es_superadmin_inicial boolean := lower(new.email) = 'superadmin@harinas-elizondo.local';
begin
  insert into public.perfiles (
    id,
    correo,
    nombre,
    rol,
    aprobado,
    aprobado_en
  )
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data ->> 'nombre', split_part(new.email, '@', 1)),
    case
      when es_superadmin_inicial then 'superadmin'::public.rol_usuario
      else 'operador'::public.rol_usuario
    end,
    es_superadmin_inicial,
    case
      when es_superadmin_inicial then timezone('utc', now())
      else null
    end
  )
  on conflict (id) do update
  set
    correo = excluded.correo,
    nombre = coalesce(public.perfiles.nombre, excluded.nombre);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.crear_perfil_usuario();

create table if not exists public.productos (
  id_producto bigint generated by default as identity primary key,
  clave text not null unique,
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now())
);

create table if not exists public.clientes (
  id_cliente integer primary key,
  nombre text not null,
  rfc text not null unique,
  domicilio_fiscal text not null,
  domicilio_entrega text,
  contacto_certificado text,
  correo_contacto_cliente text,
  correo_almacenista text,
  correo_gte_calidad text,
  documento_especificaciones text,
  solicita_certificado boolean not null default false,
  usa_especificaciones_cliente boolean not null default false,
  status text not null default 'activo'
    check (status in ('activo', 'inactivo', 'baja')),
  motivo_status text,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  creado_por uuid references auth.users (id),
  actualizado_por uuid references auth.users (id),
  constraint clientes_id_cliente_chk check (id_cliente between 100000 and 999999)
);

create table if not exists public.direcciones (
  id_direccion bigint generated by default as identity primary key,
  id_cliente integer not null references public.clientes (id_cliente) on delete cascade,
  etiqueta text not null default 'entrega',
  direccion text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now())
);

create table if not exists public.param_ref_cliente (
  id bigint generated by default as identity primary key,
  id_cliente integer not null references public.clientes (id_cliente) on delete cascade,
  id_producto bigint references public.productos (id_producto) on delete set null,
  clave_parametro text not null,
  nombre text not null,
  unidad_medida text,
  lim_min numeric(12, 4),
  lim_max numeric(12, 4),
  origen_limites text not null default 'cliente'
    check (origen_limites in ('cliente', 'internacional')),
  documento_referencia text,
  activo boolean not null default true,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  constraint param_ref_cliente_limites_chk check (
    lim_min is null
    or lim_max is null
    or lim_min <= lim_max
  ),
  constraint param_ref_cliente_unico unique (id_cliente, id_producto, clave_parametro)
);

create table if not exists public.equipos_laboratorio (
  id_equipo bigint generated by default as identity primary key,
  clave text not null unique,
  tipo text not null default 'otro'
    check (tipo in ('alveografo', 'farinografo', 'otro')),
  descripcion_larga text not null,
  descripcion_corta text,
  marca text,
  modelo text,
  serie text,
  proveedor text,
  fecha_adquisicion date,
  garantia text,
  vigencia_garantia date,
  ubicacion text,
  responsable text,
  mantenimiento text,
  status text not null default 'activo'
    check (status in ('activo', 'inactivo', 'baja')),
  motivo_status text,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  creado_por uuid references auth.users (id),
  actualizado_por uuid references auth.users (id)
);

create table if not exists public.parametros_calidad (
  id_parametro bigint generated by default as identity primary key,
  clave text not null unique,
  nombre text not null,
  unidad_medida text,
  equipo_origen text not null default 'otro'
    check (equipo_origen in ('alveografo', 'farinografo', 'otro')),
  descripcion text,
  activo boolean not null default true,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now())
);

create table if not exists public.equipos_parametros (
  id bigint generated by default as identity primary key,
  id_equipo bigint not null references public.equipos_laboratorio (id_equipo) on delete cascade,
  id_parametro bigint not null references public.parametros_calidad (id_parametro) on delete restrict,
  desviacion_permitida numeric(12, 4),
  lim_min_internacional numeric(12, 4),
  lim_max_internacional numeric(12, 4),
  especificacion_interna text,
  activo boolean not null default true,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  constraint equipos_parametros_limites_chk check (
    lim_min_internacional is null
    or lim_max_internacional is null
    or lim_min_internacional <= lim_max_internacional
  ),
  constraint equipos_parametros_unico unique (id_equipo, id_parametro)
);

create table if not exists public.lotes_produccion (
  id_lote bigint generated by default as identity primary key,
  numero_lote text not null unique,
  id_producto bigint references public.productos (id_producto) on delete set null,
  variedad text,
  fecha_produccion date,
  fecha_caducidad date,
  observaciones text,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  creado_por uuid references auth.users (id),
  actualizado_por uuid references auth.users (id)
);

create table if not exists public.inspecciones (
  id_inspeccion bigint generated by default as identity primary key,
  id_lote bigint not null references public.lotes_produccion (id_lote) on delete cascade,
  id_cliente integer references public.clientes (id_cliente) on delete set null,
  secuencia char(1) not null check (secuencia ~ '^[A-Z]$'),
  tipo_origen text not null default 'medicion'
    check (tipo_origen in ('medicion', 'ajuste', 'certificado')),
  es_ajuste boolean not null default false,
  id_inspeccion_base bigint references public.inspecciones (id_inspeccion) on delete set null,
  motivo_ajuste text,
  observaciones text,
  status text not null default 'borrador'
    check (status in ('borrador', 'cerrada', 'aprobada', 'cancelada')),
  fecha_inspeccion timestamptz not null default timezone('utc', now()),
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  creada_por uuid references auth.users (id),
  actualizada_por uuid references auth.users (id),
  constraint inspecciones_lote_secuencia_unico unique (id_lote, secuencia)
);

create or replace function public.siguiente_secuencia_inspeccion(p_id_lote bigint)
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  ultima_secuencia text;
begin
  select max(secuencia::text)
  into ultima_secuencia
  from public.inspecciones
  where id_lote = p_id_lote;

  if ultima_secuencia is null then
    return 'A';
  end if;

  if ultima_secuencia >= 'Z' then
    return null;
  end if;

  return chr(ascii(ultima_secuencia) + 1);
end;
$$;

create table if not exists public.resultados_analisis (
  id_resultado bigint generated by default as identity primary key,
  id_inspeccion bigint not null references public.inspecciones (id_inspeccion) on delete cascade,
  id_parametro bigint not null references public.parametros_calidad (id_parametro) on delete restrict,
  id_equipo bigint references public.equipos_laboratorio (id_equipo) on delete set null,
  valor numeric(12, 4),
  valor_texto text,
  unidad_medida text,
  lim_min_aplicado numeric(12, 4),
  lim_max_aplicado numeric(12, 4),
  origen_limites text not null default 'internacional'
    check (origen_limites in ('internacional', 'cliente', 'interno')),
  desviacion numeric(12, 4),
  dentro_especificacion boolean,
  observaciones text,
  capturado_en timestamptz not null default timezone('utc', now()),
  capturado_por uuid references auth.users (id),
  actualizado_en timestamptz not null default timezone('utc', now()),
  actualizado_por uuid references auth.users (id),
  constraint resultados_analisis_valor_chk check (
    valor is not null or valor_texto is not null
  ),
  constraint resultados_analisis_limites_chk check (
    lim_min_aplicado is null
    or lim_max_aplicado is null
    or lim_min_aplicado <= lim_max_aplicado
  ),
  constraint resultados_analisis_unico unique (id_inspeccion, id_parametro)
);

create table if not exists public.certificados_calidad (
  id_certificado bigint generated by default as identity primary key,
  folio text unique,
  id_cliente integer not null references public.clientes (id_cliente) on delete restrict,
  id_lote bigint not null references public.lotes_produccion (id_lote) on delete restrict,
  id_inspeccion bigint not null references public.inspecciones (id_inspeccion) on delete restrict,
  numero_orden_compra text,
  cantidad_solicitada numeric(12, 2),
  cantidad_total_entrega numeric(12, 2),
  numero_factura text,
  fecha_envio date,
  fecha_caducidad date,
  correo_cliente text,
  correo_almacen text,
  status_certificado text not null default 'borrador'
    check (status_certificado in ('borrador', 'emitido', 'cancelado')),
  status_envio text not null default 'pendiente'
    check (status_envio in ('pendiente', 'enviado', 'fallido')),
  pdf_storage_path text,
  pdf_nombre_archivo text,
  observaciones text,
  emitido_en timestamptz,
  creado_en timestamptz not null default timezone('utc', now()),
  actualizado_en timestamptz not null default timezone('utc', now()),
  emitido_por uuid references auth.users (id),
  actualizado_por uuid references auth.users (id)
);

create table if not exists public.certificado_resultados (
  id bigint generated by default as identity primary key,
  id_certificado bigint not null references public.certificados_calidad (id_certificado) on delete cascade,
  id_parametro bigint references public.parametros_calidad (id_parametro) on delete set null,
  clave_parametro text,
  nombre_parametro text not null,
  unidad_medida text,
  valor numeric(12, 4),
  valor_texto text,
  lim_min_aplicado numeric(12, 4),
  lim_max_aplicado numeric(12, 4),
  desviacion numeric(12, 4),
  dentro_especificacion boolean,
  origen_limites text,
  observaciones text
);

create table if not exists public.auditoria_eventos (
  id bigint generated by default as identity primary key,
  entidad text not null,
  entidad_id text not null,
  accion text not null,
  descripcion text,
  motivo text,
  valores_anteriores jsonb not null default '{}'::jsonb,
  valores_nuevos jsonb not null default '{}'::jsonb,
  usuario_id uuid references auth.users (id),
  creado_en timestamptz not null default timezone('utc', now())
);

create index if not exists perfiles_aprobado_idx on public.perfiles (aprobado);
create index if not exists perfiles_rol_idx on public.perfiles (rol);
create index if not exists clientes_status_idx on public.clientes (status);
create index if not exists clientes_solicita_certificado_idx on public.clientes (solicita_certificado);
create index if not exists direcciones_cliente_idx on public.direcciones (id_cliente, activo);
create index if not exists param_ref_cliente_id_cliente_idx on public.param_ref_cliente (id_cliente, activo);
create index if not exists equipos_laboratorio_status_idx on public.equipos_laboratorio (status);
create index if not exists parametros_calidad_equipo_origen_idx on public.parametros_calidad (equipo_origen, activo);
create index if not exists equipos_parametros_equipo_idx on public.equipos_parametros (id_equipo, activo);
create index if not exists lotes_produccion_producto_idx on public.lotes_produccion (id_producto);
create index if not exists inspecciones_lote_idx on public.inspecciones (id_lote, secuencia);
create index if not exists inspecciones_cliente_idx on public.inspecciones (id_cliente, fecha_inspeccion desc);
create index if not exists resultados_analisis_inspeccion_idx on public.resultados_analisis (id_inspeccion);
create index if not exists resultados_analisis_parametro_idx on public.resultados_analisis (id_parametro);
create index if not exists certificados_calidad_cliente_idx on public.certificados_calidad (id_cliente, creado_en desc);
create index if not exists certificados_calidad_lote_idx on public.certificados_calidad (id_lote);
create index if not exists certificados_calidad_inspeccion_idx on public.certificados_calidad (id_inspeccion);
create index if not exists auditoria_eventos_entidad_idx on public.auditoria_eventos (entidad, entidad_id, creado_en desc);

drop trigger if exists productos_tocar_actualizado_en on public.productos;
create trigger productos_tocar_actualizado_en
before update on public.productos
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists clientes_tocar_actualizado_en on public.clientes;
create trigger clientes_tocar_actualizado_en
before update on public.clientes
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists direcciones_tocar_actualizado_en on public.direcciones;
create trigger direcciones_tocar_actualizado_en
before update on public.direcciones
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists param_ref_cliente_tocar_actualizado_en on public.param_ref_cliente;
create trigger param_ref_cliente_tocar_actualizado_en
before update on public.param_ref_cliente
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists equipos_laboratorio_tocar_actualizado_en on public.equipos_laboratorio;
create trigger equipos_laboratorio_tocar_actualizado_en
before update on public.equipos_laboratorio
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists parametros_calidad_tocar_actualizado_en on public.parametros_calidad;
create trigger parametros_calidad_tocar_actualizado_en
before update on public.parametros_calidad
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists equipos_parametros_tocar_actualizado_en on public.equipos_parametros;
create trigger equipos_parametros_tocar_actualizado_en
before update on public.equipos_parametros
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists lotes_produccion_tocar_actualizado_en on public.lotes_produccion;
create trigger lotes_produccion_tocar_actualizado_en
before update on public.lotes_produccion
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists inspecciones_tocar_actualizado_en on public.inspecciones;
create trigger inspecciones_tocar_actualizado_en
before update on public.inspecciones
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists resultados_analisis_tocar_actualizado_en on public.resultados_analisis;
create trigger resultados_analisis_tocar_actualizado_en
before update on public.resultados_analisis
for each row
execute procedure public.tocar_actualizado_en();

drop trigger if exists certificados_calidad_tocar_actualizado_en on public.certificados_calidad;
create trigger certificados_calidad_tocar_actualizado_en
before update on public.certificados_calidad
for each row
execute procedure public.tocar_actualizado_en();

alter table public.perfiles enable row level security;
alter table public.productos enable row level security;
alter table public.clientes enable row level security;
alter table public.direcciones enable row level security;
alter table public.param_ref_cliente enable row level security;
alter table public.equipos_laboratorio enable row level security;
alter table public.parametros_calidad enable row level security;
alter table public.equipos_parametros enable row level security;
alter table public.lotes_produccion enable row level security;
alter table public.inspecciones enable row level security;
alter table public.resultados_analisis enable row level security;
alter table public.certificados_calidad enable row level security;
alter table public.certificado_resultados enable row level security;
alter table public.auditoria_eventos enable row level security;

grant usage on schema public to authenticated;
grant select on public.perfiles to authenticated;
grant select, insert, update on public.productos to authenticated;
grant select, insert, update on public.clientes to authenticated;
grant select, insert, update, delete on public.direcciones to authenticated;
grant select, insert, update, delete on public.param_ref_cliente to authenticated;
grant select, insert, update on public.equipos_laboratorio to authenticated;
grant select, insert, update on public.parametros_calidad to authenticated;
grant select, insert, update, delete on public.equipos_parametros to authenticated;
grant select, insert, update on public.lotes_produccion to authenticated;
grant select, insert, update on public.inspecciones to authenticated;
grant select, insert, update, delete on public.resultados_analisis to authenticated;
grant select, insert, update on public.certificados_calidad to authenticated;
grant select, insert, update on public.certificado_resultados to authenticated;
grant select, insert on public.auditoria_eventos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "El usuario ve su propio perfil" on public.perfiles;
create policy "El usuario ve su propio perfil"
on public.perfiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Admin ve todos los perfiles" on public.perfiles;
create policy "Admin ve todos los perfiles"
on public.perfiles
for select
to authenticated
using (public.usuario_actual_es_admin());

drop policy if exists "Productos visibles para aprobados" on public.productos;
create policy "Productos visibles para aprobados"
on public.productos
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Productos editables para aprobados" on public.productos;
create policy "Productos editables para aprobados"
on public.productos
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Clientes visibles para aprobados" on public.clientes;
create policy "Clientes visibles para aprobados"
on public.clientes
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Clientes editables para aprobados" on public.clientes;
create policy "Clientes editables para aprobados"
on public.clientes
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Direcciones visibles para aprobados" on public.direcciones;
create policy "Direcciones visibles para aprobados"
on public.direcciones
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Direcciones editables para aprobados" on public.direcciones;
create policy "Direcciones editables para aprobados"
on public.direcciones
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Parametros cliente visibles para aprobados" on public.param_ref_cliente;
create policy "Parametros cliente visibles para aprobados"
on public.param_ref_cliente
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Parametros cliente editables para aprobados" on public.param_ref_cliente;
create policy "Parametros cliente editables para aprobados"
on public.param_ref_cliente
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Equipos visibles para aprobados" on public.equipos_laboratorio;
create policy "Equipos visibles para aprobados"
on public.equipos_laboratorio
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Equipos editables para aprobados" on public.equipos_laboratorio;
create policy "Equipos editables para aprobados"
on public.equipos_laboratorio
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Parametros visibles para aprobados" on public.parametros_calidad;
create policy "Parametros visibles para aprobados"
on public.parametros_calidad
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Parametros editables para aprobados" on public.parametros_calidad;
create policy "Parametros editables para aprobados"
on public.parametros_calidad
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Equipos parametros visibles para aprobados" on public.equipos_parametros;
create policy "Equipos parametros visibles para aprobados"
on public.equipos_parametros
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Equipos parametros editables para aprobados" on public.equipos_parametros;
create policy "Equipos parametros editables para aprobados"
on public.equipos_parametros
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Lotes visibles para aprobados" on public.lotes_produccion;
create policy "Lotes visibles para aprobados"
on public.lotes_produccion
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Lotes editables para aprobados" on public.lotes_produccion;
create policy "Lotes editables para aprobados"
on public.lotes_produccion
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Inspecciones visibles para aprobados" on public.inspecciones;
create policy "Inspecciones visibles para aprobados"
on public.inspecciones
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Inspecciones editables para aprobados" on public.inspecciones;
create policy "Inspecciones editables para aprobados"
on public.inspecciones
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Resultados visibles para aprobados" on public.resultados_analisis;
create policy "Resultados visibles para aprobados"
on public.resultados_analisis
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Resultados editables para aprobados" on public.resultados_analisis;
create policy "Resultados editables para aprobados"
on public.resultados_analisis
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Certificados visibles para aprobados" on public.certificados_calidad;
create policy "Certificados visibles para aprobados"
on public.certificados_calidad
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Certificados editables para aprobados" on public.certificados_calidad;
create policy "Certificados editables para aprobados"
on public.certificados_calidad
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Certificado resultados visibles para aprobados" on public.certificado_resultados;
create policy "Certificado resultados visibles para aprobados"
on public.certificado_resultados
for select
to authenticated
using (public.usuario_actual_aprobado());

drop policy if exists "Certificado resultados editables para aprobados" on public.certificado_resultados;
create policy "Certificado resultados editables para aprobados"
on public.certificado_resultados
for all
to authenticated
using (public.usuario_actual_aprobado())
with check (public.usuario_actual_aprobado());

drop policy if exists "Auditoria visible para admins" on public.auditoria_eventos;
create policy "Auditoria visible para admins"
on public.auditoria_eventos
for select
to authenticated
using (public.usuario_actual_es_admin());

drop policy if exists "Auditoria insertable para aprobados" on public.auditoria_eventos;
create policy "Auditoria insertable para aprobados"
on public.auditoria_eventos
for insert
to authenticated
with check (public.usuario_actual_aprobado());

insert into public.parametros_calidad (
  clave,
  nombre,
  unidad_medida,
  equipo_origen,
  descripcion
)
values
  ('ALV_P', 'Tenacidad', null, 'alveografo', 'Parametro P del alveografo.'),
  ('ALV_L', 'Extensibilidad', null, 'alveografo', 'Parametro L del alveografo.'),
  ('ALV_W', 'Fuerza panadera', null, 'alveografo', 'Parametro W del alveografo.'),
  ('ALV_S', 'Area de la curva', null, 'alveografo', 'Parametro S del alveografo.'),
  ('ALV_PL', 'Relacion P/L', null, 'alveografo', 'Relacion de configuracion de la curva.'),
  ('FAR_ABS', 'Absorcion de agua', null, 'farinografo', 'Absorcion de agua de la harina.'),
  ('FAR_DES', 'Tiempo de desarrollo', null, 'farinografo', 'Tiempo de desarrollo de la masa.'),
  ('FAR_EST', 'Estabilidad', null, 'farinografo', 'Estabilidad de la masa.'),
  ('FAR_REB', 'Grado de reblandecimiento', null, 'farinografo', 'Debilitamiento o reblandecimiento de la masa.'),
  ('FAR_FQN', 'Numero de calidad', null, 'farinografo', 'Farinograph Quality Number.')
on conflict (clave) do nothing;
